hash-format = "sha256"

[[files]]
file = "config/cameraoverhaul.json"
hash = "ced32e5c6d2eed851df693a255c4dd13f3ae18ab75d52f63771d8cbcb7572d8b"

[[files]]
file = "config/capes.json5"
hash = "f09322c29a146b50b87d79186776aba7e6220fe0f7e16602027715f1f73c7dec"

[[files]]
file = "config/chatpatches.json"
hash = "ede726243ddd41ed65555fa9cff88076366a38bf405372fa67643f0ca11af0fc"

[[files]]
file = "config/dynamicfps.toml"
hash = "cd21d3f612a4b704d314a848840567ede751ded584bcc07bb1e186eeb7e76cc2"

[[files]]
file = "config/fabrizoom.conf"
hash = "6500022fe5ea57706347a3fbd300d7bdbb8793a2d04c5cde1905caa6d7337a82"

[[files]]
file = "config/fallingleaves.json"
hash = "0173cf1b8ba7a3fceeb73982f194d36f2bc89f6191cca8cb8d9c3223d463dde2"

[[files]]
file = "config/fancymenu/config.txt"
hash = "973c474a34323b463e0b4597e885b825e59f4bc14ea0aa19b26c0a5ea57fe733"

[[files]]
file = "config/fancymenu/customguis/wynnic_function_stock.txt"
hash = "35c3a1a47aea751c30a0aadf6a31ca4ae67a3ad181757d82402e6a2c2c7457f2"

[[files]]
file = "config/fancymenu/customizablemenus.txt"
hash = "01cc3b615d86a983073d42921a054dbeeaad4caf5259534872de2883ab023bef"

[[files]]
file = "config/fancymenu/customization/WynnicMenu.txt"
hash = "e694d2e69dd2d057c772d5a01b81e728799e3cd1877dd31f16503f902e7489b6"

[[files]]
file = "config/fancymenu/customization/custom_bar.txt"
hash = "5228769124e8ee17cf2d180dbb8d5c5ca94a3a8e6e029aa7c1cc87416ef6ba33"

[[files]]
file = "config/fancymenu/customization/info_box.txt"
hash = "5d091f6a4d1bca155216d4198e09e340d36e85005f980144c06b7f10b8b03498"

[[files]]
file = "config/fancymenu/customization/wynn_load.txt"
hash = "b53b4be9ca2f83bea1ca0886923179e8269d7573efeb8119f5057513b15bd7b8"

[[files]]
file = "config/fancymenu/customization/wynnic_functions.txt"
hash = "49d74bd1a44f69dd32c574615b4f77a803d27ed094d14b9b6f605a3a7fdddba0"

[[files]]
file = "config/fancymenu/customization/wynnic_pause.txt"
hash = "5c978850a1aa29fbc6c3fc9c27ec94bc40130e81796d43a6e981d60dff7198f8"

[[files]]
file = "config/fancymenu/locals/de_de.local"
hash = "5a6e49aa18f4e113a96832b2d386046c199a86293aa573200d9df67c2d938b58"

[[files]]
file = "config/fancymenu/locals/en_us.local"
hash = "f301202074cf1bdf43a5f1ea78c317340a43647dd4b88a11c33b32b41dad8a14"

[[files]]
file = "config/fancymenu/locals/pl_pl.local"
hash = "de116f0404dfba5a2ac1f61d15d7aae198ab8e0cf7402148d0018b3ab3e08e45"

[[files]]
file = "config/fancymenu/locals/pt_br.local"
hash = "afd40caa6c2681f9aa0efca3d05dc68d9415d206a052d33fb31dceae9765ebfd"

[[files]]
file = "config/fancymenu/locals/zh_cn.local"
hash = "0fe06b353073577fe10811f5d01b4ef1e677a02386a5e46e6f3e27da48777f47"

[[files]]
file = "config/fancymenu/menu_identifiers.db"
hash = "003a1c89846741e0eb9475089d4ed653896fd08e0b994667fae452b4ad894a72"

[[files]]
file = "config/fancymenu/minecraftwindow/icons/icon16x16.png"
hash = "8df663b65090e05a4043643aaf4c9969f0466eba6343eadb3369c1e983bcb5c7"

[[files]]
file = "config/fancymenu/minecraftwindow/icons/icon32x32.png"
hash = "17e419377517944c7a61c76bbc6e1594e411082672a7c60ec2de87c5933bc4fd"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/Corkus.png"
hash = "22d2cee6aca03db23225f6635bb148a928ec1d8d50db33bff0f6146ae168d7ad"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/Detlas North Entrance.png"
hash = "93159715fafe6c057ce59186ae26040b59300645a4e182dc6b8447723b7d9e8b"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/East Entrance to Detlas.png"
hash = "96db0a76df334e20a25a94e105c32792094a3b59ee15def3040b2dc2025d76ab"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/Entrance to Nivla Woods.png"
hash = "5e44f82a99b6ac1a1f359ccbb413d6839bf49d11d5c17d6e90e5968ed755eb55"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/Guild Hall Entrance.png"
hash = "459f5d0cb5392b1e31c5c91e064ab862c876482a4defcad92369fd5dcf892118"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/Llevigar.png"
hash = "4b2d6c0faeb9167e6e32ba65251b4a8a95379ad04ee1851d427bf06639ca5695"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/Nest of the Grootslangs external.png"
hash = "d75c7b5d5ed25610bed6b2b15f61dfa316f0f077207980156df793d56c154b02"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/Nether Portal.png"
hash = "6d86a7d6db3a5d055c0b339f9d1bacff8aa035169d14b4388ab5eb50ee3352b7"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/Realm of light exterior.png"
hash = "8659457950a2890d15e188d8f936e50d9ec088865237fa454b3cc266a000595f"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/Sand Swept Tomb Entrance.png"
hash = "f19075129ddae3f292f81937068705edbf1cff976c93e321acf60a69ed48f91c"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/Selchar Port.png"
hash = "83ec5f05372f53148b73cf0e0e27f22a33205a2b4ad9f0db4605e84db4691e78"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/Sky islands.png"
hash = "ac66b1f12b70c85e254ecc985e916b464a87ddbbe7623528323bcc7f921b8388"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/The Hive.png"
hash = "3e4eb0a3fec1ba320c6ab4714bb933e6de632fd0bc5ef948d203d6bde87cc0fd"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/The Tree.png"
hash = "f30e2ad79f36837917757dee10eab8a8b675c742be6943787cfda9b71065a9be"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/View of Nessak Wilderness + Ice Barrows Dungeon.png"
hash = "01d8c606adedb017ac31253be757326a8e91585b37bb03b32908cbd24b456d8b"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/Wynn Excavation Site.png"
hash = "ba5b977fcc50fb0cabcc5ae0c11496e5c3a16de4320c7095c5e99cea7b3f9c79"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/small lake at the entrance to the Rymek Region.png"
hash = "4de4161841eeaca39faf8c42db55265b110be5a762564a39513e2f701576ae2f"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/properties.txt"
hash = "638cc2a76567b69abf94f8b7d5de63a94f3a4ae10c6222611564da4d40af0dc4"

[[files]]
file = "config/fancymenu/user_variables.db"
hash = "f27db2df244107a607158267a180cf1ad0adcd33b582e0394aa58b690a25806e"

[[files]]
file = "config/halohud.json5"
hash = "c14b4450a51209e679926e94e5459cb6b776bb64e888e4c0f1546cd56ba0c597"

[[files]]
file = "config/legendarytooltips-common.toml"
hash = "b7f925c32449b2582338808f88845e511151d2cd19ae34e75efdeff6796bcb17"

[[files]]
file = "config/nimble-client.toml"
hash = "424d302d2b8d62d88ed163b6de913cb506f2c5a71a260e0343bb5da27e21a811"

[[files]]
file = "config/notenoughanimations.json"
hash = "c9c80b79df3497277e10290addc0206b3915472dfcbcfb3b933fc50abe7ca034"

[[files]]
file = "config/physicsmod/physics_animations_client_config.json"
hash = "d8a629b25da461374926b02b6649ed90154cb1bb6ab7e5208f519b5bcf29b08b"

[[files]]
file = "config/physicsmod/physics_blocks_client_config.json"
hash = "31616a74c8531224b1ca2ad19e6c1dbde50c2dbf902e80fe6f2a3625c8a852e9"

[[files]]
file = "config/physicsmod/physics_client_config.json"
hash = "61b398c633112f8ff8591375ef95956249df61ce958c8dea8501308b9bf7711c"

[[files]]
file = "config/physicsmod/physics_cloth_config.json"
hash = "91955763ff613b21fcb25717e47c7c8f217da1c7dd7a04e57af57633c8da2e0a"

[[files]]
file = "config/physicsmod/physics_mobs_client_config.json"
hash = "752775debf65550a6a11ae2cc27c6f5c649cb8ac833a496e5c222d484bc63c14"

[[files]]
file = "config/physicsmod/physics_server_config.json"
hash = "1afde48eff108eb21adb246de5d44ef6ced16862cca62cf0123c059a9934c7cc"

[[files]]
file = "config/physicsmod/physics_vines_client_config.json"
hash = "f0f5d28f52effe8ab66fb6c1b33863befa1f77887dc479db50cb49bad69a9772"

[[files]]
file = "config/smoothswapping.json"
hash = "8e552f11575f5d0fef350b323fd7c0c55e652e313fc0da0e82e21b0659744541"

[[files]]
file = "config/waveycapes.json"
hash = "7674f91a618d1dca348a8685c6ff4fce64500ed0058dea5b6cb56b8603eff611"

[[files]]
file = "fancymenu/changelog.txt"
hash = "76d2573d443050ac850b59160dbcef4a188fca67ecc8a52f51380320c821559d"

[[files]]
file = "fancymenu/kofi.png"
hash = "37c9c9a1fb8f8d4cb7da948c4ba8943552ec7a7a458d8dbc39719881597aa950"

[[files]]
file = "fancymenu/logomain-old.png"
hash = "3ea583e449658093c3f13adfeceb978f76a68b35b6a9533dd43db50decd59c64"

[[files]]
file = "fancymenu/logomain-oldnew.png"
hash = "f2f87bd1a67142bfe5666a38087fd56f906301e34eafe5b0cea0c9709fcfe2f7"

[[files]]
file = "fancymenu/logomain.png"
hash = "f7ad6769125dd28800c99e0f4926a8e98b0d4281ae275b26a73ee49fdbdf05f5"

[[files]]
file = "fancymenu/mastodon.png"
hash = "fe3a919327fc4f574e151818c5f7ef0162df82871db962227533a42f2456587b"

[[files]]
file = "fancymenu/modrinth.png"
hash = "c3f0424d244d1bd136c3087e3234b9ed9a0cd0e74e1f20bf890a394a0c67af72"

[[files]]
file = "fancymenu/spectra.png"
hash = "507195c3a756d8edc88592f8fb7427cadaf6f4056bc74f90ffb44b8f85cfd9a2"

[[files]]
file = "fancymenu/version.txt"
hash = "78041001f249f9eaa2aec2bd63e5db741b4c96958cecdf068cc346fe4f2d6ae5"

[[files]]
file = "fancymenu/version2.json"
hash = "cc4ec95dcf01194349ede787dd0c01610bc80ff0378e8ca782359108208b325b"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "8868e7077cfcb26792ae0e366577400ee26c74b9fb9da550cd8570829c97020f"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "64b30aca719ec164ad4da2c3ff40030e7ed0eb53c104b55a358c8aa5c0849753"
metafile = true

[[files]]
file = "mods/better-third-person.pw.toml"
hash = "9c44cf229440021ac7c42cd265fcec944fb002e2264c61688dfc21546bdaed5d"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "d63cdad6d5f15a1e1fa4e465de9b8302ee9044412bb209e29ea05cfd94d46dbc"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
hash = "66112808be4535b813a5294d662c3b466b18eec2347460c0066ffb229717014f"
metafile = true

[[files]]
file = "mods/borderless-mining.pw.toml"
hash = "5cc5a514cc9b8567abda1d5860a8ac3afdf868906caf9bd24c6c534943e1fb4c"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "9ab9f1ada10bc693019cdfea96fa09bcbaa3f27c8350e2e23fc45927f838cd9b"
metafile = true

[[files]]
file = "mods/cameraoverhaul.pw.toml"
hash = "c6ea5427c8ffe56b90b495b3f070d6f12ee2adc87b5a3c4aebd46c29c2dfc2b1"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "617563db0d44229fb65eb660130d02d1a4d2f29233eda03b68d3273e700326f8"
metafile = true

[[files]]
file = "mods/chatpatches.pw.toml"
hash = "f906f1ec2a08c61770475ee3c270040781047d03ef6a5db132c6d1c4b21ed169"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "1fc52599bb002e467661afaa4b844c517fb549ad14eb6f552bf11dfb5c8b535e"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "fe65086f792f8d98cb7c9a8dbe429fff9645b30717874e8cf46b23a8487bc531"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "b63d8794c73eea90c3ff396beb75bf1001ec6139d9a32f655437990d0950c775"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "c3db7d59e69e69067942dd7e5bfd71bb10ca823c60198c92727c071f022f2789"
metafile = true

[[files]]
file = "mods/custom-fov-illusive.pw.toml"
hash = "fa2aea3461ede4e442a0c6512b7bf76e7b42250e8e4d962ce604373ab9e943e5"
metafile = true

[[files]]
file = "mods/drippy-loading-screen.pw.toml"
hash = "8acf775fd75a8c2315250380f875d85e1e9b94069ddae2ca1db15ffbadc4feed"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "6e6ee1bf66d6977728d3bf5404338c87a0a4ad5260833efcd912aaaca776cf8f"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "15bcf9dadaa40f2e05987b8171cfc9c3007224751c379789b984de7223dddbb8"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "625dddd14bf47324a945452cbd92e913877bb574883b086a73aa6fc07740ac44"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "dadd7e05239ea864bd5ec6606a4c3948b29da94b2d3bc89b027aa7be84d13678"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "714158dafbd5954a8024d5b7e677fc1303d1c0bc665c7df5942d3a685904988e"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "6f95b9e670d557f852a798489d7b5ec48ed8ddc7e8e1809ff06d4b187d17aac9"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "eadfa683575620f77806518a35e822bad539aac6358c94db82272751d5c6961d"
metafile = true

[[files]]
file = "mods/fabrizoom.pw.toml"
hash = "35c7ff1c1c93accf52af005941def3e6a6cb01202884dee8ebccd3a7ef631282"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "0c4c20d601b15dbc85c275732d9efe9369597503c7d6caa9a7fee217f67073e7"
metafile = true

[[files]]
file = "mods/fancymenu.pw.toml"
hash = "65d2038f170287c9a8f1cdb79cb8d2f5f15ad5112ab561737c9c0ded428e961b"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "03e174cf691b52da20bd973b955fae6f3720d3d2120f9d6cc1de5fdf3180013c"
metafile = true

[[files]]
file = "mods/first-person-model.pw.toml"
hash = "7b0d86d39312310c82be70ea1e86fd0bd05fefbefe5cd66691bfbb94f532f0a9"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "e00070f0db00ebcd304f8f68fd44e59ceaedbc8c27743c9c195134aae57c5fde"
metafile = true

[[files]]
file = "mods/halohud.pw.toml"
hash = "c7d3f7fb5a6b5e18f149c4ae909798e2f42862229d01c23717087e29730e471d"
metafile = true

[[files]]
file = "mods/iceberg.pw.toml"
hash = "a4d47f10df4769734a850e6a2cd7342802f92f5e269b27464c86cfd0b5a2182f"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "7e9f6a5b564e4fbe92bff784eb13a2565eb5a631ed452cf9b8748e73935ae8b2"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "0c5e71addef34c8dcd1c81dfc2ad851a3e274b9d8d3a7d388e1113d4139bf8d8"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "e60dfe0d44555b200e0ab643f7beaa90dde3d37c5e89fea7dcf11f94f581f5ae"
metafile = true

[[files]]
file = "mods/item-highlighter.pw.toml"
hash = "c5d5b857fa70cb5deed260054b9723dc8069635880061d5ba328e1eb684604bf"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "d75446972bdb7bdaa4c16b366557b167690649d0f916a24947ff2b6bc6b33821"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "f999930809222b57898da25a30aad2135b02894f42c0e1d2832c4670272fbd1d"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "a2e62ebd7ce3187f7aa004aed7e4d11975104ae590ba1d3eb0ec319c30581574"
metafile = true

[[files]]
file = "mods/legendary-tooltips.pw.toml"
hash = "4c418d76137ed1a34686a7f667348c97b5f457b28ae1469152aa35f44c4e9a1f"
metafile = true

[[files]]
file = "mods/libjf.pw.toml"
hash = "497a0ebb0287f2a2d813a59e706f5e472b501c2b5a66508d195e3d3fbea10794"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "ed27ecb297016accc41e9894b6e11d6c46b455211e358afa6218ce629ef56978"
metafile = true

[[files]]
file = "mods/mica.pw.toml"
hash = "f16f06375bc2a889a503a09409ebf3ffb7174d245a4a3dbbdf6d090a6cb2e4b1"
metafile = true

[[files]]
file = "mods/midnightcontrols.pw.toml"
hash = "6a89a7b2f668a64d3cbabe81ead17322ed734e60f846a6c0ab2f99745d8c712e"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "7dc0119dac2246a00a28a73c128bc2e5275fa8c61dfb6024ef75476691c95a00"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "6c417b19bc836d7c516be0097261c49cf1a167951bb4744ec0f3cc0bd0d1d24a"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "74466c118cfcd7b89ccfc3841a4bf9421e762079b584807ca8651d6145b3afd8"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "b136ca50e7d8239319f528ceb521e3482f753b25d768afaf39fa6ea81e549f2e"
metafile = true

[[files]]
file = "mods/mods-command.pw.toml"
hash = "3f986955b1fec4bada6e3240d055ecf550456a0c2aa36629de7b25233e9baaf5"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "be1f88824f7ceb008ce38ae763a93921db0c27db68577fdb16c29c6a085ec1f3"
metafile = true

[[files]]
file = "mods/nicer-skies.pw.toml"
hash = "740561bdea8bc9be18c80f740b05e51a8ff890b1e2ba7edb6d04ba936faaceed"
metafile = true

[[files]]
file = "mods/nimble.pw.toml"
hash = "1c969c386599caaabc4704b20497ba9e8f10eaf4b589aa37d90141aca7dec62f"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "fbab079e97ad9d05574071f0586494ded680553d460533bdb99d85d2cdb57bdf"
metafile = true

[[files]]
file = "mods/physicsmod.pw.toml"
hash = "a67351d0cff0948610067de873938095a61cd9f65cc4dc70faede89d19e7e060"
metafile = true

[[files]]
file = "mods/prism-lib.pw.toml"
hash = "e51bce9d59f8db31f2730a742b84917a3729388f2fc44e0aa51fa39f9dfb43d5"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "19a098ab3131eb6daf0033199744d33dbb31a4ce9b20b9fc6eb709ab1272aa7e"
metafile = true

[[files]]
file = "mods/respackopts.pw.toml"
hash = "d1933e5bae58b915ad72da111370cc94a353bcee2a0e19afcf7013dba22bd23c"
metafile = true

[[files]]
file = "mods/screenshot-to-clipboard.pw.toml"
hash = "53a945b8cd854887c8d8ac1297990f2309e97c1aa372dfd5706b740488e7f451"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "5a0076258f4597639ee178da994e4eefe223392dad47cf6cb24da2ab26d9ace8"
metafile = true

[[files]]
file = "mods/server-pack-unlocker.pw.toml"
hash = "e50f824096c786528a4ff6e610f48aaeec638111c27660eb3f455882bee8ef2a"
metafile = true

[[files]]
file = "mods/smooth-swapping.pw.toml"
hash = "5a523fb19287c6ce690ed0b7986e07e7002b878d980204226c3cde04e85baa77"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "7e39ba5b471407bf43c212fae99856276bf4411046aa3a5df5a7d27e76c7a2b3"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "ff614f50beb3bc29a699dbcc0a61f65bd6c6154cd374f2763ee57cf578045a8f"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "1f922cadccd8b79e824e78d5e2e691e65127e7a500723121a6a6ccc6a1060289"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "0a78a506125c0edc97d2292d26c6eab310106c60a5a4e64d73ff67bb619f5a4c"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "1d0b62685fd74fdd9d8cba3b3f3a85da75423550704646251a39542fce96bcb4"
metafile = true

[[files]]
file = "mods/wavey-capes.pw.toml"
hash = "c1a73e1365c070187293067ac39295b45ea3bcf933166d9bed9a0a8bd3762874"
metafile = true

[[files]]
file = "mods/wynntils.pw.toml"
hash = "3b2b7a56d1b914a72cb5b1d0dea76d5e8c3ba2c0df3c2673f497f103a8e07be3"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "46d3f8c4c1bfc8f92858d7e405aed9d1a23e554a783f8977662cbeca06eda5f2"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "8c6e70cd43376bef19f3496e90932ad43ab53c9bb71c3169d1d03e58209d1bf5"
metafile = true

[[files]]
file = "shaderpacks/vanillaa.pw.toml"
hash = "b062f3d3717d82a0359fbf09472339e7080026fce69fc4a6d136ac8266b9e6ec"
metafile = true
