hash-format = "sha256"

[[files]]
file = "config/capes.json5"
hash = "f09322c29a146b50b87d79186776aba7e6220fe0f7e16602027715f1f73c7dec"

[[files]]
file = "config/dynamicfps.toml"
hash = "cd21d3f612a4b704d314a848840567ede751ded584bcc07bb1e186eeb7e76cc2"

[[files]]
file = "config/fallingleaves.json"
hash = "0173cf1b8ba7a3fceeb73982f194d36f2bc89f6191cca8cb8d9c3223d463dde2"

[[files]]
file = "config/fancymenu/config.txt"
hash = "698ab48868e7ab8ae36696cdd23047b66fac0d09d8b2af65244df25da141e61c"

[[files]]
file = "config/fancymenu/customizablemenus.txt"
hash = "6f839fad9a09709e9c2d1b269218da6a515ea31495575de5bdbc901147740327"

[[files]]
file = "config/fancymenu/customization/WynnicMenu.txt"
hash = "985d5909b6d8378df81c0aeec30447b3e6d8d6862bce396fdfbade17336dc46f"

[[files]]
file = "config/fancymenu/locals/de_de.local"
hash = "13485f1d678322a328e798c34f1ff9f7f9c690464d1050e2e7c1ea02b0f49b61"

[[files]]
file = "config/fancymenu/locals/en_us.local"
hash = "6e5f6a7fce57921106335d54801ca78557bfb7db45bb10122240ec9fb6503b34"

[[files]]
file = "config/fancymenu/locals/pl_pl.local"
hash = "66d4e9b270d4d92bffd85b13255def475d3ff6c865965deaa700be2ed1b08bc0"

[[files]]
file = "config/fancymenu/locals/pt_br.local"
hash = "0b19fc1d8bd8c86435eb39886116aceb3b4554fa749561fc87be2df0157a134c"

[[files]]
file = "config/fancymenu/locals/zh_cn.local"
hash = "50cf30919fd2c7b11f6ce246425d657e3b93dfb919a0b6fe4730dc5d9fee0d2a"

[[files]]
file = "config/fancymenu/menu_identifiers.db"
hash = "003a1c89846741e0eb9475089d4ed653896fd08e0b994667fae452b4ad894a72"

[[files]]
file = "config/fancymenu/minecraftwindow/icons/icon16x16.png"
hash = "5067420a2be7adb406a8e88502cecc37bd570d65c9765489ce90cef2a8ecfdb2"

[[files]]
file = "config/fancymenu/minecraftwindow/icons/icon32x32.png"
hash = "9f6517c6f209db516bfa5159c9b84cfbe2f640517e498379520d70f310d1bf2e"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/Corkus.png"
hash = "22d2cee6aca03db23225f6635bb148a928ec1d8d50db33bff0f6146ae168d7ad"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/Detlas North Entrance.png"
hash = "93159715fafe6c057ce59186ae26040b59300645a4e182dc6b8447723b7d9e8b"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/East Entrance to Detlas.png"
hash = "96db0a76df334e20a25a94e105c32792094a3b59ee15def3040b2dc2025d76ab"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/Entrance to Nivla Woods.png"
hash = "5e44f82a99b6ac1a1f359ccbb413d6839bf49d11d5c17d6e90e5968ed755eb55"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/Guild Hall Entrance.png"
hash = "459f5d0cb5392b1e31c5c91e064ab862c876482a4defcad92369fd5dcf892118"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/Llevigar.png"
hash = "4b2d6c0faeb9167e6e32ba65251b4a8a95379ad04ee1851d427bf06639ca5695"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/Nest of the Grootslangs external.png"
hash = "d75c7b5d5ed25610bed6b2b15f61dfa316f0f077207980156df793d56c154b02"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/Nether Portal.png"
hash = "6d86a7d6db3a5d055c0b339f9d1bacff8aa035169d14b4388ab5eb50ee3352b7"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/Realm of light exterior.png"
hash = "8659457950a2890d15e188d8f936e50d9ec088865237fa454b3cc266a000595f"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/Sand Swept Tomb Entrance.png"
hash = "f19075129ddae3f292f81937068705edbf1cff976c93e321acf60a69ed48f91c"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/Selchar Port.png"
hash = "83ec5f05372f53148b73cf0e0e27f22a33205a2b4ad9f0db4605e84db4691e78"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/Sky islands.png"
hash = "ac66b1f12b70c85e254ecc985e916b464a87ddbbe7623528323bcc7f921b8388"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/The Hive.png"
hash = "3e4eb0a3fec1ba320c6ab4714bb933e6de632fd0bc5ef948d203d6bde87cc0fd"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/The Tree.png"
hash = "f30e2ad79f36837917757dee10eab8a8b675c742be6943787cfda9b71065a9be"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/View of Nessak Wilderness + Ice Barrows Dungeon.png"
hash = "01d8c606adedb017ac31253be757326a8e91585b37bb03b32908cbd24b456d8b"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/Wynn Excavation Site.png"
hash = "ba5b977fcc50fb0cabcc5ae0c11496e5c3a16de4320c7095c5e99cea7b3f9c79"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/small lake at the entrance to the Rymek Region.png"
hash = "4de4161841eeaca39faf8c42db55265b110be5a762564a39513e2f701576ae2f"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/properties.txt"
hash = "638cc2a76567b69abf94f8b7d5de63a94f3a4ae10c6222611564da4d40af0dc4"

[[files]]
file = "config/fancymenu/user_variables.db"
hash = "d2d55a621e0ca0765db2ffc20084e053b090e9076516e83b88a65b57a6d33557"

[[files]]
file = "config/smoothswapping.json"
hash = "8e552f11575f5d0fef350b323fd7c0c55e652e313fc0da0e82e21b0659744541"

[[files]]
file = "config/waveycapes.json"
hash = "ce39b32f5938f759dfc5385f0a51f4836df558b0972af7037497fb5e745d8db5"

[[files]]
file = "fancymenu/gradient.png"
hash = "70514fd04aacc4b5adad22e1ec88fafc98be57fb5734c261b555a77e129bdbf5"

[[files]]
file = "fancymenu/logomain.png"
hash = "3ea583e449658093c3f13adfeceb978f76a68b35b6a9533dd43db50decd59c64"

[[files]]
file = "fancymenu/version.txt"
hash = "831095209d323df5774389889a40265594e0ed2497b17a9f494a0959056edff2"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "99b55d449ddb9e75fa3a32e7b681b2d5f1074388ad6d67cd8e37e9b6b176418a"
metafile = true

[[files]]
file = "mods/amecs.pw.toml"
hash = "036e1eec012427f093c426a7e43781ed221c28790e0a73e953e31b692cb05d49"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "11fe9da06043756e637e29d0e051f6745a788464a551808534162a96616c8615"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
hash = "afe7690d3e28211f06ec27b666f56951508ecda78aef7aae3fede8426a24d2c8"
metafile = true

[[files]]
file = "mods/borderless-mining.pw.toml"
hash = "a85833a7ea20b38e5524f2755f4288b62045fd7155ca071c6d4cc1dc9b8c2958"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "b1ff809ec34348860c3a403f3d5210f7386ddcda8f0d19c5ff4533fd22abeb08"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "aade03c8feebb27bf28d42bf481f642385531536e40d22857a5ea542be6cf437"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "981329cf6f43e84fab85b6a1f976738fd5df594030e9f43d6bd6dea330eafb47"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "07708d8f6b49da8c4deb77f7fea0dda45b471ec46a5191363c7bec8d63c23769"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "0f8269bf3c425efd7c76d48dda7f48523ed5171fe2e341c6cb926d06c67cc9ff"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "ecd6d665190c7deeec2b86bd68397001e3be57c6e2e562b8c8a77da412d4bf74"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "1b6d3b3242c76ac3b3b81206f470d28f3b4d1d09af450ed358688ea5f8abde14"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "f6bc53688790ec2d88c96568f6d7569bf0111931c569cf64b511cdbe95090c82"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "c985bc9064cc29094fdfd59a037baa1523778cc2a9e5665c3f1b6ca0efe6a543"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "27fb80e740a5a151475280d6b91968a567885b0b20f402b098c6bae546aec699"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "7fce7db18aa8459a0404fd862175ccabe36b3f6f03286136f548b6bdc91abc23"
metafile = true

[[files]]
file = "mods/fancymenu.pw.toml"
hash = "815bae89b799283e2f5fb7382dfe56bbf7c97af8c39469e14f2ac5bff13ce6b1"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "b119d700005f53f8fb07ff342546eb20918206a115f247932422ab304169d33e"
metafile = true

[[files]]
file = "mods/figura.pw.toml"
hash = "8ab49d9b93ab65ebc217d9b45f2fe78d17de9c94b28c03d251574200d829496a"
metafile = true

[[files]]
file = "mods/first-person-model.pw.toml"
hash = "037642da6cd5470a74db68df2f1d445ac1eeca74ee5930fcd2e6cb7da3459a9a"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "1ab5733b357d9c788c357802d9052d952699dd905aeed81b41370169fab70c11"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "7d3727ee323a1e3e6a41719db11e343e0658cc149274b9d4426acc9ae21b1363"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "8856c3a4587c6bca5fdcecc39d246291802ace8f76a815547470dca14ad6202a"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "fe272e09a500f94981c2415f55f988e4cb36a3b289ccc5ae59a5d9a8255e4f99"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "a2e62ebd7ce3187f7aa004aed7e4d11975104ae590ba1d3eb0ec319c30581574"
metafile = true

[[files]]
file = "mods/libjf.pw.toml"
hash = "4728c69f91275a2adc025d43d5ad7e194a5ff6848ffaaf82633505ab5630c7eb"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "a016e55e2b77e59aa41e8cb786eaf7fdb766ba3f0314de952d7bbd4634e57dd8"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "5b43c0fc6904ad4480c8ed596411c6e24172f8320ccd63de97b4ce2e7e0f90a5"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "7dc0119dac2246a00a28a73c128bc2e5275fa8c61dfb6024ef75476691c95a00"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "edc7cc205be8c2a9fe5a4634ba64d2dd803ae5d31d79343917c398a9b8e8dd5d"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d6c6f9a833db51587789b59ab8b7f711e394ec616ace9597cc41b22a93a4a68f"
metafile = true

[[files]]
file = "mods/mods-command.pw.toml"
hash = "7dfc3da9cc351cd96d3ac0b87d976355d527a752dfc8a6f7afd526de1534ebd9"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "e850143ae4200eeb18b83a6530f7e01edc0d328330fced9097d771c08bc21216"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "ad4a221b5135b6e4fe977e360a60b7df32b33951e510667027d5c3ee986659da"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "971a22fbc96da08fb68053e6ffb0ca4186d1ab9efbba0fcf8aa244f9c8ac7098"
metafile = true

[[files]]
file = "mods/respackopts.pw.toml"
hash = "fc4dbea2031b197c7f18dc69c3458fa8cea4c687a8387bba4a0a80befefaccb8"
metafile = true

[[files]]
file = "mods/screenshot-to-clipboard.pw.toml"
hash = "53a945b8cd854887c8d8ac1297990f2309e97c1aa372dfd5706b740488e7f451"
metafile = true

[[files]]
file = "mods/server-pack-unlocker.pw.toml"
hash = "722b03f1b827220389751fa503c2ad4b9af636e2073780f9dfed64ae2a6ce1bc"
metafile = true

[[files]]
file = "mods/smooth-swapping.pw.toml"
hash = "dc0eeb3a6c59aca637ace46238ae952b263add5f0aebae644b11471478a4eb4f"
metafile = true

[[files]]
file = "mods/smoothboot-fabric.pw.toml"
hash = "7c0c3fdc225b1938ba7dc03cc06c3bc7e6e127617d6c1ffc77db1384f7544a75"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "c253e367bc570cbdcad5cd5ee759a918548bb2e9c641b8a460a73bc637d79b74"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "cff6e118a7d2649ab479bbcf328d463349cfc8dc4bac3f5025395f34c2b505bb"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "60dbdc5acba0392fa923fbbae580d216f2a3dac4b7ab8056fe28e7e4de8331f2"
metafile = true

[[files]]
file = "mods/tooltip-scroll.pw.toml"
hash = "b640641526c660cffb2d2b8a9ac74e93a65c0d27a77cdc98336fdbef348c708c"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "61722d9c82bdd59e4449e222caa09bab363075422c6fc8aba361b1c61fd257eb"
metafile = true

[[files]]
file = "mods/vtdownloader.pw.toml"
hash = "b51a50229aad084e4980f6dd1651b56a2c7a6a60b45854cafac99b7074703825"
metafile = true

[[files]]
file = "mods/wavey-capes.pw.toml"
hash = "5b046f76bc01d9a11b49d14eb3cc286b2a0e43558d36a49dc767a7fc1a922b29"
metafile = true

[[files]]
file = "mods/wynntils.pw.toml"
hash = "89b41e348f6884f0a5c5b99b3b8703b610124069d361ddebc3f01c8156070954"
metafile = true
