hash-format = "sha256"

[[files]]
file = "config/capes.json5"
hash = "f09322c29a146b50b87d79186776aba7e6220fe0f7e16602027715f1f73c7dec"

[[files]]
file = "config/dynamicfps.toml"
hash = "cd21d3f612a4b704d314a848840567ede751ded584bcc07bb1e186eeb7e76cc2"

[[files]]
file = "config/fallingleaves.json"
hash = "0173cf1b8ba7a3fceeb73982f194d36f2bc89f6191cca8cb8d9c3223d463dde2"

[[files]]
file = "config/fancymenu/config.txt"
hash = "698ab48868e7ab8ae36696cdd23047b66fac0d09d8b2af65244df25da141e61c"

[[files]]
file = "config/fancymenu/customizablemenus.txt"
hash = "6f839fad9a09709e9c2d1b269218da6a515ea31495575de5bdbc901147740327"

[[files]]
file = "config/fancymenu/customization/WynnicMenu.txt"
hash = "42c8605e59fa3c3eb28f7d295433465af5fbc8f5bb2e40cc1be8b0273dda98f8"

[[files]]
file = "config/fancymenu/customization/wynn_load.txt"
hash = "de0230935db266e6347cf62b5ca3df3ddaeb4b9c9ecea947ba767fe33f4da27b"

[[files]]
file = "config/fancymenu/locals/de_de.local"
hash = "13485f1d678322a328e798c34f1ff9f7f9c690464d1050e2e7c1ea02b0f49b61"

[[files]]
file = "config/fancymenu/locals/en_us.local"
hash = "6e5f6a7fce57921106335d54801ca78557bfb7db45bb10122240ec9fb6503b34"

[[files]]
file = "config/fancymenu/locals/pl_pl.local"
hash = "66d4e9b270d4d92bffd85b13255def475d3ff6c865965deaa700be2ed1b08bc0"

[[files]]
file = "config/fancymenu/locals/pt_br.local"
hash = "0b19fc1d8bd8c86435eb39886116aceb3b4554fa749561fc87be2df0157a134c"

[[files]]
file = "config/fancymenu/locals/zh_cn.local"
hash = "50cf30919fd2c7b11f6ce246425d657e3b93dfb919a0b6fe4730dc5d9fee0d2a"

[[files]]
file = "config/fancymenu/menu_identifiers.db"
hash = "003a1c89846741e0eb9475089d4ed653896fd08e0b994667fae452b4ad894a72"

[[files]]
file = "config/fancymenu/minecraftwindow/icons/icon16x16.png"
hash = "152f8f2945d830b960a5a053ea4c3357c23cb6b6a509115f176a91084fc280c7"

[[files]]
file = "config/fancymenu/minecraftwindow/icons/icon32x32.png"
hash = "8c39a16638ad260ac34e765a6470767238b266adbd790b7847db2dbadf5508f3"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/Corkus.png"
hash = "22d2cee6aca03db23225f6635bb148a928ec1d8d50db33bff0f6146ae168d7ad"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/Detlas North Entrance.png"
hash = "93159715fafe6c057ce59186ae26040b59300645a4e182dc6b8447723b7d9e8b"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/East Entrance to Detlas.png"
hash = "96db0a76df334e20a25a94e105c32792094a3b59ee15def3040b2dc2025d76ab"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/Entrance to Nivla Woods.png"
hash = "5e44f82a99b6ac1a1f359ccbb413d6839bf49d11d5c17d6e90e5968ed755eb55"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/Guild Hall Entrance.png"
hash = "459f5d0cb5392b1e31c5c91e064ab862c876482a4defcad92369fd5dcf892118"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/Llevigar.png"
hash = "4b2d6c0faeb9167e6e32ba65251b4a8a95379ad04ee1851d427bf06639ca5695"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/Nest of the Grootslangs external.png"
hash = "d75c7b5d5ed25610bed6b2b15f61dfa316f0f077207980156df793d56c154b02"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/Nether Portal.png"
hash = "6d86a7d6db3a5d055c0b339f9d1bacff8aa035169d14b4388ab5eb50ee3352b7"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/Realm of light exterior.png"
hash = "8659457950a2890d15e188d8f936e50d9ec088865237fa454b3cc266a000595f"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/Sand Swept Tomb Entrance.png"
hash = "f19075129ddae3f292f81937068705edbf1cff976c93e321acf60a69ed48f91c"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/Selchar Port.png"
hash = "83ec5f05372f53148b73cf0e0e27f22a33205a2b4ad9f0db4605e84db4691e78"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/Sky islands.png"
hash = "ac66b1f12b70c85e254ecc985e916b464a87ddbbe7623528323bcc7f921b8388"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/The Hive.png"
hash = "3e4eb0a3fec1ba320c6ab4714bb933e6de632fd0bc5ef948d203d6bde87cc0fd"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/The Tree.png"
hash = "f30e2ad79f36837917757dee10eab8a8b675c742be6943787cfda9b71065a9be"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/View of Nessak Wilderness + Ice Barrows Dungeon.png"
hash = "01d8c606adedb017ac31253be757326a8e91585b37bb03b32908cbd24b456d8b"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/Wynn Excavation Site.png"
hash = "ba5b977fcc50fb0cabcc5ae0c11496e5c3a16de4320c7095c5e99cea7b3f9c79"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/images/small lake at the entrance to the Rymek Region.png"
hash = "4de4161841eeaca39faf8c42db55265b110be5a762564a39513e2f701576ae2f"

[[files]]
file = "config/fancymenu/slideshows/wynnic_main/properties.txt"
hash = "638cc2a76567b69abf94f8b7d5de63a94f3a4ae10c6222611564da4d40af0dc4"

[[files]]
file = "config/fancymenu/user_variables.db"
hash = "d2d55a621e0ca0765db2ffc20084e053b090e9076516e83b88a65b57a6d33557"

[[files]]
file = "config/halohud.json"
hash = "e277f9041a17506b059569adec5cebc29260982d3ed6b8d789d3088a53282a69"

[[files]]
file = "config/legendarytooltips-common.toml"
hash = "b7f925c32449b2582338808f88845e511151d2cd19ae34e75efdeff6796bcb17"

[[files]]
file = "config/nimble-client.toml"
hash = "5321dae8041a23bdfc55b12ddbc14caeecc2b36574ae4bc746e0d250d5e76191"

[[files]]
file = "config/smoothswapping.json"
hash = "8e552f11575f5d0fef350b323fd7c0c55e652e313fc0da0e82e21b0659744541"

[[files]]
file = "config/waveycapes.json"
hash = "73b0cc19c51755c2622e5ea09700519ad26fa724469ffb2e34ae7e3edb55262e"

[[files]]
file = "fancymenu/gradient.png"
hash = "70514fd04aacc4b5adad22e1ec88fafc98be57fb5734c261b555a77e129bdbf5"

[[files]]
file = "fancymenu/logomain-old.png"
hash = "3ea583e449658093c3f13adfeceb978f76a68b35b6a9533dd43db50decd59c64"

[[files]]
file = "fancymenu/logomain.png"
hash = "f2f87bd1a67142bfe5666a38087fd56f906301e34eafe5b0cea0c9709fcfe2f7"

[[files]]
file = "fancymenu/version.txt"
hash = "4c6936f74a70a113c495fb9ef6b94d42898fa714e7cc001754d859047c2730d2"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "c61f1e575d6acf7ef4233f15100db8e870b3c5d2898c910bcf4a10d0dc5534a9"
metafile = true

[[files]]
file = "mods/amecs.pw.toml"
hash = "036e1eec012427f093c426a7e43781ed221c28790e0a73e953e31b692cb05d49"
metafile = true

[[files]]
file = "mods/auth-me.pw.toml"
hash = "f0eac2832b0c04d4994683decf8bd1a4cf69fd3b12b5a735bf0138c5b59799b5"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "11fe9da06043756e637e29d0e051f6745a788464a551808534162a96616c8615"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
hash = "afe7690d3e28211f06ec27b666f56951508ecda78aef7aae3fede8426a24d2c8"
metafile = true

[[files]]
file = "mods/borderless-mining.pw.toml"
hash = "a85833a7ea20b38e5524f2755f4288b62045fd7155ca071c6d4cc1dc9b8c2958"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "b1ff809ec34348860c3a403f3d5210f7386ddcda8f0d19c5ff4533fd22abeb08"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "83d8a8865dfe81276fabc0c7085106a760608c0a3d569716fc77b3d0cb4d4c0d"
metafile = true

[[files]]
file = "mods/chime.pw.toml"
hash = "573c77af3df0ddda601b8e048bfa5c808f31577f7954261b0c7386a3bb8b2abb"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "981329cf6f43e84fab85b6a1f976738fd5df594030e9f43d6bd6dea330eafb47"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "44ff1ee89feb34b51ed41e5841eb54bbd1e5ea112f117789c66bbd8b032bf592"
metafile = true

[[files]]
file = "mods/drippy-loading-screen.pw.toml"
hash = "e4978202b3666677b84ce6aed44ab464b6db50a320fc57adaf53cf728ccb9231"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "0f8269bf3c425efd7c76d48dda7f48523ed5171fe2e341c6cb926d06c67cc9ff"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "beaf8fcc2dbc9098a414bedd5a8ca156084b39f20517fac2ff60ad57f5767202"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "b9e92b5e0baed5a916779ef0016172d2d42ea310d9742744a8c920ecee4d7b9a"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "3631c36fa685ff8b408b83f41cb5ed62d44a10314247a379c20bceaae32ce88b"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "3ecd59b2ab957aadc6759fdb82b82d63c03dfef49c1199f271078659e94cdbf1"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "27fb80e740a5a151475280d6b91968a567885b0b20f402b098c6bae546aec699"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "9892a0024b5f2aeb4dbb9b39f3ebc518c4661ba31b487dd332b879ba22bcc4fd"
metafile = true

[[files]]
file = "mods/fancymenu.pw.toml"
hash = "b4e21b654ec27fd131311633ce4d5413141f5cefb05115b3230ff6fc69610e73"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "b119d700005f53f8fb07ff342546eb20918206a115f247932422ab304169d33e"
metafile = true

[[files]]
file = "mods/figura.pw.toml"
hash = "3ff2fb81009cc392b8349ee264593f25490f89e72e35d059f67655dcd9d346db"
metafile = true

[[files]]
file = "mods/first-person-model.pw.toml"
hash = "a9446c4a0ddeb25dd57bf0054d66b40e310acfbd7d21aef706c20ca692ea1f5d"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "141d7b9b7aacccafe753464bc0171b33e54b778fd40cf458ac2b3ac051329e8d"
metafile = true

[[files]]
file = "mods/halohud.pw.toml"
hash = "a850d587fecfe462eedc1d45132888426159d59bddc29a0a430a57f17600f542"
metafile = true

[[files]]
file = "mods/iceberg.pw.toml"
hash = "4c414176e5197b04f07913765a3d7df161939d1201f0b315772bc5189cb41a43"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "064fafff245baf812342dc9af4acf661dec663bab2a4067c65a27fa00860efb1"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "09d31307f81a06df5ab65ff57c2c830180bbc1138bb8326557172b0a883d6b8b"
metafile = true

[[files]]
file = "mods/kiwi.pw.toml"
hash = "35af87969cf3261b6e4c89744fd1a262597edb9ade4e522ad952e8339b76ea01"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "50d0e93b73a48e2822927e3c484993430be3bfc7936e0013b4bd7d8b2b6754aa"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "fe272e09a500f94981c2415f55f988e4cb36a3b289ccc5ae59a5d9a8255e4f99"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "a2e62ebd7ce3187f7aa004aed7e4d11975104ae590ba1d3eb0ec319c30581574"
metafile = true

[[files]]
file = "mods/legendary-tooltips.pw.toml"
hash = "14ce404ea055cad362d146cf2bbc0d7573aa1761f04b503acbe1f8f3798e063e"
metafile = true

[[files]]
file = "mods/libjf.pw.toml"
hash = "33681397442de23d0d392528bb348a4bb0b7e914e06b347220388bd7b32a1306"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "6682a581b77e820ea340d3279b7a49f5d311d3fa0b08b53628c9bf56a7c668ac"
metafile = true

[[files]]
file = "mods/logical-zoom.pw.toml"
hash = "c33d4c86ca2416368635e5cef98bf8babb019b74eb77249ceedaed81812494fd"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "2f1393d78824d3e665be954e339affed26d8482d227aa3f13d6ca5d577469f8b"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "7dc0119dac2246a00a28a73c128bc2e5275fa8c61dfb6024ef75476691c95a00"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "47fff2ed63e342e95bf9a0ad086d896148195bbcbc25260300ca1b27d454f7b8"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "c6932018158da544553f88b977bed1946f59d9c86685f2023b0a9ee196fc3087"
metafile = true

[[files]]
file = "mods/mods-command.pw.toml"
hash = "071d5111fb0bbc02502302b85e29f9a49fc7f8950a54aaf2e1db3a9906c39984"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "bbf63ac8b9775c315526e0161daa609493a9a6168741077aca636e0123a2a4f4"
metafile = true

[[files]]
file = "mods/nimble.pw.toml"
hash = "34dec2a1e4a38f477422068766749695b7de5a469fd7d063deabf8dd8a9089a2"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "bf4bc45cf15ca007c159e1a963e5924e3663eb986ebabe2d79df2a7894f665de"
metafile = true

[[files]]
file = "mods/prism-lib.pw.toml"
hash = "f572e6d256c0b89039db1ac239593e0f4d0027d3944a5c814dfdd6967da6fd35"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "971a22fbc96da08fb68053e6ffb0ca4186d1ab9efbba0fcf8aa244f9c8ac7098"
metafile = true

[[files]]
file = "mods/respackopts.pw.toml"
hash = "fc4dbea2031b197c7f18dc69c3458fa8cea4c687a8387bba4a0a80befefaccb8"
metafile = true

[[files]]
file = "mods/screenshot-to-clipboard.pw.toml"
hash = "53a945b8cd854887c8d8ac1297990f2309e97c1aa372dfd5706b740488e7f451"
metafile = true

[[files]]
file = "mods/server-pack-unlocker.pw.toml"
hash = "722b03f1b827220389751fa503c2ad4b9af636e2073780f9dfed64ae2a6ce1bc"
metafile = true

[[files]]
file = "mods/smooth-swapping.pw.toml"
hash = "741f07735108747dfd4083ea061712221b72a85137a71012c33cfa144d1a185a"
metafile = true

[[files]]
file = "mods/smoothboot-fabric.pw.toml"
hash = "7c0c3fdc225b1938ba7dc03cc06c3bc7e6e127617d6c1ffc77db1384f7544a75"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "4b3e56fec52c8a95bb59e11f745be3a5ed8a527714cb4b5fb8ac5b7bf3cc662f"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "1ab96020d0954a72b5cc150b375f57cf8968ac2c1809a000472076f8675eb9ea"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "60dbdc5acba0392fa923fbbae580d216f2a3dac4b7ab8056fe28e7e4de8331f2"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "f8f5e1897e2250f3a715b33b6c7efd3e7ec7142556d68e17a38c71833d23e3ba"
metafile = true

[[files]]
file = "mods/vtdownloader.pw.toml"
hash = "892e2b6f34132cbff1015f2f5b1de1e3a2ddb22d3a0dc7ab762821b80654390d"
metafile = true

[[files]]
file = "mods/wavey-capes.pw.toml"
hash = "ecf0c6a4e1ea923de5149d8fbceb63c2030d9d89385c08289483695d012f5568"
metafile = true

[[files]]
file = "mods/wynntils.pw.toml"
hash = "3e8566eca1ef6766fe72474329656a4a023f01b1788aca995c1083ccefe2f8a0"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "c66028d555a347562589645179fe8834bd04d48b78c9a667f20b4178211dfbb3"
metafile = true

[[files]]
file = "shaderpacks/vanillaa.pw.toml"
hash = "5def7fe470d25c729d7356c856984ab517e8cbcdf0b01eced72aa1dc95accb3b"
metafile = true
