hash-format = "sha256"

[[files]]
file = "config/cameraoverhaul.json"
hash = "ced32e5c6d2eed851df693a255c4dd13f3ae18ab75d52f63771d8cbcb7572d8b"

[[files]]
file = "config/capes.json5"
hash = "f09322c29a146b50b87d79186776aba7e6220fe0f7e16602027715f1f73c7dec"

[[files]]
file = "config/chatpatches.json"
hash = "ede726243ddd41ed65555fa9cff88076366a38bf405372fa67643f0ca11af0fc"

[[files]]
file = "config/defaultoptions/keybindings.txt"
hash = "2e621b306e33a230aca4e1c2e1e2101fe000e2ad620de4005d9231c38e8d845c"

[[files]]
file = "config/drippyloadingscreen/options.txt"
hash = "e0e8c50f3d6fe28a59f79d8977e300c1ac7aaa7ded151b80532009779f3cd6dc"

[[files]]
file = "config/dynamicfps.toml"
hash = "cd21d3f612a4b704d314a848840567ede751ded584bcc07bb1e186eeb7e76cc2"

[[files]]
file = "config/fabrizoom.conf"
hash = "6500022fe5ea57706347a3fbd300d7bdbb8793a2d04c5cde1905caa6d7337a82"

[[files]]
file = "config/fallingleaves.json"
hash = "0173cf1b8ba7a3fceeb73982f194d36f2bc89f6191cca8cb8d9c3223d463dde2"

[[files]]
file = "config/flow.config.json"
hash = "e23707eeb315182111f4df3719f119a434dcb5cf04a46a9f819d596994c24b67"

[[files]]
file = "config/halohud.json5"
hash = "25f7b588915744fd6c2ff6b1c0851bcb6c0bd87642739eb57d4c4ab24ff5ab07"

[[files]]
file = "config/legendarytooltips-common.toml"
hash = "b7f925c32449b2582338808f88845e511151d2cd19ae34e75efdeff6796bcb17"

[[files]]
file = "config/modpack-update-checker-info.txt"
hash = "e34f089454e2b27550bfdecc38a2f4f99980853a8564d578dcb2f3b1ee11bd51"

[[files]]
file = "config/modpack-update-checker/config.json"
hash = "f3652a492dd244a01854d916f50e73178c8cd14102bd8bd2e77d0d865b0d59cf"

[[files]]
file = "config/nimble-client.toml"
hash = "424d302d2b8d62d88ed163b6de913cb506f2c5a71a260e0343bb5da27e21a811"

[[files]]
file = "config/notenoughanimations.json"
hash = "c9c80b79df3497277e10290addc0206b3915472dfcbcfb3b933fc50abe7ca034"

[[files]]
file = "config/physicsmod/physics_animations_client_config.json"
hash = "d8a629b25da461374926b02b6649ed90154cb1bb6ab7e5208f519b5bcf29b08b"

[[files]]
file = "config/physicsmod/physics_blocks_client_config.json"
hash = "31616a74c8531224b1ca2ad19e6c1dbde50c2dbf902e80fe6f2a3625c8a852e9"

[[files]]
file = "config/physicsmod/physics_client_config.json"
hash = "6b0a280202912ea35b244bfd958e67afeac2cf9bde38de0f3fc04c5a0690434d"

[[files]]
file = "config/physicsmod/physics_cloth_config.json"
hash = "91955763ff613b21fcb25717e47c7c8f217da1c7dd7a04e57af57633c8da2e0a"

[[files]]
file = "config/physicsmod/physics_mobs_client_config.json"
hash = "8573ae2afa100c63bb1775a5e7adb2f0e089c7e8ffe2810c6ba4e9cb59053c00"

[[files]]
file = "config/physicsmod/physics_server_config.json"
hash = "1afde48eff108eb21adb246de5d44ef6ced16862cca62cf0123c059a9934c7cc"

[[files]]
file = "config/physicsmod/physics_vines_client_config.json"
hash = "f0f5d28f52effe8ab66fb6c1b33863befa1f77887dc479db50cb49bad69a9772"

[[files]]
file = "config/sounds.ui.config.json"
hash = "b6b3cec60afe46528106f0c52a66f6fe365b0b83c3db9f2afca4f5e28a9bba4a"

[[files]]
file = "config/sounds/chat.json"
hash = "53bd643eda071581cc13734cd2e949e13f172dda1da06f61a55599f7c3a5607c"

[[files]]
file = "config/sounds/event.json"
hash = "2d7e2faf7782a225d8010deb00042bf30509a6bfd5b238e86fa1c6972f12d71f"

[[files]]
file = "config/sounds/ui.json"
hash = "1bf20d1fb124d63e4e87bf21d6c66b034facf81a4459c7bb5d02627780287c72"

[[files]]
file = "config/sounds/world.json"
hash = "b823c547a0013865bcb814b0a00e7b2914a2f90ca5a3f674974977a434ef6006"

[[files]]
file = "config/waveycapes.json"
hash = "7674f91a618d1dca348a8685c6ff4fce64500ed0058dea5b6cb56b8603eff611"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "6e4a1ad878793ab3c3b7df30ea8e4177a65c3632d1b35277683d6f6b333cb073"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "0543bf0e7d7ac48e221c7e97b55ca7add1c8a1a4b9c5d487688782472fe287b9"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "58134b8f4cca95555746efad25cc8a56c39ed57ba05f78d3aa61b603d378180c"
metafile = true

[[files]]
file = "mods/auth-me.pw.toml"
hash = "3efb5df489cdac5c07964f7d2d6bcb8f0464f76e55b4397ed85f9e378fa1a784"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "70627f1d5caeee154224403abf974f4ca83a03d63e1914c3d7505cdaf338c0d4"
metafile = true

[[files]]
file = "mods/better-third-person.pw.toml"
hash = "cb177f0ebdb9eca2126fea8e837a0cdc5f3c3f3ad28381871748c55d84c29206"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "7c801232a6e7b3930c6c6f47f2c4cd77a539f28bc41e6d54e1710c2736d8a46f"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
hash = "5e0adbaf5a22a684b1691eea9a8c4daa6b1eb2b5d821ac83c558ef015d15d51a"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "a4fd2e20e1a2444c6892e9f14d94b1b8802a8a4954f9e3e49045aac9b9074f23"
metafile = true

[[files]]
file = "mods/cameraoverhaul.pw.toml"
hash = "33b7b0f1a2f027f70e48f4b58447bcb2b9591d47c0322fc0dafb449f924b2183"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "df21d4923d61c8d9199e602cca45695b7d17295fa8555f072d8d83045946ef3e"
metafile = true

[[files]]
file = "mods/chatpatches.pw.toml"
hash = "6cd8354be5fbe8d9c369c0702156cc39352acfe36be593974a0d7ffec75283cf"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "d345d14d9672063419184ece254b77a51386160916058bb24a4af7faabc88d99"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "c6564e6bd7f9fef3ac5d07340b09df6529f807ad358bf8156f05d6fc9a4f751b"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "0f24f7bd2057b70b6816de4e66922b64f8b6635dc603e40cc45d62646dc7221d"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "3d7e89c47e6c0fe58d947d21aef262a3e92cb098c9ace3d90e50cc91f1f88053"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "9162c0544dfbffc867c4dfec239ebe7fb6b0b73c3a78ef1d0917748467a57bbf"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "f8a561f0ac371a33d5e5c4f3a525b5aaca4161b391f46505eac4e1a1d4895902"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "11699829fc65c378c5bcccbea9375304ce6194aed18d2f02ee733ed44879efb4"
metafile = true

[[files]]
file = "mods/custom-fov-illusive.pw.toml"
hash = "3bf1f6cb3220828fdc936ce844921906a467c04856c7c9980969a5c2bae478c7"
metafile = true

[[files]]
file = "mods/drippy-loading-screen.pw.toml"
hash = "53643da21fa7bb9501db576690a439a5fd7c7c510be32128a81a8618df8fd9c8"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "03233a7e383409b517598e0c9d10c8a45c6035a35f163d15337a7bae044c4319"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "86e971b1f82d63c791f7e7574c0ebfc9d1e4b6a23085257599ded29ed365ce6c"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "7d0b378ccbc753946b078a94fd1cac24b7b906492aa45660d4686051397a4c17"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "bd026bd6a8e0b7bd8dc6802c733d09775eead2ad40c8f243917facfcd2e33e29"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "c8215a5e6f35175c0c3d764284026b94a8159207319299081459f6aeb05b4191"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "0d8130db3f4b00b03d8e6f41f5e621308cad4288fbdcdd69bb5d5a495a681701"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "fb9771f28f1fb92ff6b6e049ce18c458f679351a782143c18407fba8546d066e"
metafile = true

[[files]]
file = "mods/fabrizoom.pw.toml"
hash = "19816b44126f65f045d732cbcd733b5b6e671cd22f7b0541edf509362470e46d"
metafile = true

[[files]]
file = "mods/fadeless.pw.toml"
hash = "3452c0877052a563c9357a17977b3466b010772010145af5ef0f1b60f31400a8"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "9b561d57bf92aa8005e567e4bb95a2b65c8ed9c3ab30de09ea6c7e66f2e4d2da"
metafile = true

[[files]]
file = "mods/fancymenu.pw.toml"
hash = "6aa695f9ceedcb76ff1a1063455d0676edfbcc35bd09465faa4ccb4c1cad2d1a"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "078c828454d8a361baae372b5ee3dc33e5f3573fa19bdac8589b38da9dbc5c03"
metafile = true

[[files]]
file = "mods/first-person-model.pw.toml"
hash = "ffb9ad3a8174df332b4a9d164409b44ba3c9ab904943c5eb0ff5a39451f80643"
metafile = true

[[files]]
file = "mods/forcecloseworldloadingscreen.pw.toml"
hash = "ecfd75bec8245e1f183258086f8f3ff62169d8172b576889bb7eab8e1b27c46c"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "21ff233990cef71ae6467ef24547227bdfae664260045086d5318d2f642861ec"
metafile = true

[[files]]
file = "mods/halohud.pw.toml"
hash = "44f305d1d8072d6cf4fd474b98ab21e9fd41b3fcc5fd50061a40a3b40537fc36"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "3f8f7b594419ea4fefa330c82fee1be6d904390b3a6bb40e52aeb8e7b9009c82"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "ec7ddc7195eaec44adb0a060c48d919bedb82775a3b683f8da21ab2eb6921ab1"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "315648c1b6910b274d4a16bda8eba7ddf380d928edb20c0c36f3ff9776e30fe5"
metafile = true

[[files]]
file = "mods/keybind-fix-plus.pw.toml"
hash = "317f7c207ba328de9318266ca96a16865f8db7ac734ba0c317e866c79a3b2aeb"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "2c7ad26f8416aee6c43dbe20397a1bd52b333028a0c592c59ff5c4e1f1af63a2"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "4ee72fa3b6d91ccec6ec3420396db368dc5097350ee2bb909af3a65f0446c9d5"
metafile = true

[[files]]
file = "mods/libjf.pw.toml"
hash = "e1b8e2e0ecd392bda24dc7cbd53788ed605ab3d8a24fbf6171939f42ecc5cdff"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "f004eac1859218b35a865698a68000b21806709f02b54b2a2ef55ff04a793328"
metafile = true

[[files]]
file = "mods/melody.pw.toml"
hash = "ab6af5e589ade8a9400eba7235ee509e66f640cd248bf3333b6001a084d63b3e"
metafile = true

[[files]]
file = "mods/mica.pw.toml"
hash = "3710f2eb2a4c0077e4ce57afd8675f846655809f3eafe4fd0caaa91dc5d3548c"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "7dc0119dac2246a00a28a73c128bc2e5275fa8c61dfb6024ef75476691c95a00"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "edebf3f514e6ae422c890a47f30340d21fbf51b4362f5d902047bd4263d9a9ee"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "ebbaf07d4e04f172081d5f4bec47837ae1008c5a6dbedc32f7ba471dd3d004cd"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "e37792db4c4b69e11243c7470f0f2a791dc016381e460cd5616eccb6b567b5ab"
metafile = true

[[files]]
file = "mods/modpack-update-checker.pw.toml"
hash = "78c7aac73d61c1df5a5e8c859457099aa8604048a881172427f827ca8bb5a2b8"
metafile = true

[[files]]
file = "mods/mods-command.pw.toml"
hash = "951251f3bb6f8d29750ef995799e80d25fef955c46b28076ac66006455753801"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "cce89b418e7dd00df7d58eb6556472385aff2f2934c4bfde1b7a2dcd3b1d17cc"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "966aafb5b4d6c70474dc6178aae033dd068579f3d5063f9e1b37f4cf813f44dd"
metafile = true

[[files]]
file = "mods/nicer-skies.pw.toml"
hash = "9c6baa56a71ce342c6c621c634e7a2573bef8bfecde08d40387e382f227a9c90"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "8221d0376bdd5c13684d44ce2dcfc994f4aeea8d21546b9a562e71517ba1ce80"
metafile = true

[[files]]
file = "mods/notes.pw.toml"
hash = "8b2b9e974b3f819d7e65a7da50dc2f7929854fb7432c18ff60bbcf32a4a80516"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "d8d16415897778ba9e6bf5cd74920edce456787f48c4e8fc6e2aa1d17fdffdc7"
metafile = true

[[files]]
file = "mods/physicsmod.pw.toml"
hash = "52b3ee843c75ecc4f57fb2a0c7753656b8ab41a2d7510bcb981e96be692c9c85"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "5bef9a443c12a13d5eeefa60bbb0a40ef99ab8a0675cd335a6cc2520dc5ba33b"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "c497424b603b0b9fc190427fd7aa0985d23a74f4cba6c554e14f7dbd29385df2"
metafile = true

[[files]]
file = "mods/respackopts.pw.toml"
hash = "780003058ae9154919ff2e788351a15fd32ff958d01aafcf215cf1c4e9c858d2"
metafile = true

[[files]]
file = "mods/screenshot-to-clipboard.pw.toml"
hash = "c803d271faae47b193e3ba9ca611894252bf55d4c6aab303f56bcf6b183056c7"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "b91df989a584b59e4834445bb2d240ff0c76cf139a6f6795d42d623d689e74fe"
metafile = true

[[files]]
file = "mods/server-pack-unlocker.pw.toml"
hash = "88cf9aced39c83537675ec3f9e54a3ec1e8a76694f5042d8bc76be3613f86edb"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "28f2167da063c1be7b1f4e534cdcbb446daa569cc32ffe1c0705663a9a06a5b9"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "280cf7ad4ec95bd95eef81a7f327095c5f40e1b8aa45cea91284bfd19395d69e"
metafile = true

[[files]]
file = "mods/sonance.pw.toml"
hash = "70c9c72ef2ea3e2c168faf2808659a51a45664627e73a407fe4080bdf0db0f6e"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "24ca44f204ce1904fa79e0fab79c101831716b3197a726f71abf6e5d3e621f80"
metafile = true

[[files]]
file = "mods/toastbegone.pw.toml"
hash = "ff24f87ff5880706e87edbdd82f3cdc2199e6bfdd7311d9116ae87e89e6e874e"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "6cb2a4cd4eb40eaf19bbb54a6d8fa23643470147e86e19fe04b820e170998ed3"
metafile = true

[[files]]
file = "mods/wavey-capes.pw.toml"
hash = "f474df1d652f6286874e95c4b754e59b52b84b12afe2e3c9162a42344426a852"
metafile = true

[[files]]
file = "mods/wynntils.pw.toml"
hash = "05ffbefd79ebb43a0f1be26f0250125279cafe8b77cd4139411afa829812ed33"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "6a22d14251ccfb61007da299c1040bcb3904bd0cc43e5d1ba96536b94ed43036"
metafile = true

[[files]]
file = "resourcepacks/wynnedits-dark-theme.pw.toml"
hash = "2079e5eb6b1212cdfa96d0ef2eb9cd6d6d1eee86a7c2791bbf6bf3d922e60d3a"
metafile = true

[[files]]
file = "resourcepacks/wynnic-elemental-tooltips.pw.toml"
hash = "43def18903e73c50527d86eddf74ea3c5aac7a851db35adacd587d15a8a2dc6b"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "6bdf4cf5d1c5da444c0ff0a5e5e1f17881006c72b519d0951f6b6521ff043601"
metafile = true

[[files]]
file = "shaderpacks/vanillaa.pw.toml"
hash = "b062f3d3717d82a0359fbf09472339e7080026fce69fc4a6d136ac8266b9e6ec"
metafile = true
