name = "Wynnic Enchantments"
author = "Rafii2198"
version = "0.16.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8cf69b1349f1764c45c49dce98cdd000224fc505b39013da264716107ec265d2"

[versions]
fabric = "0.18.4"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.3"]
