name = "Wynnic Enchantments"
author = "Rafii2198"
version = "0.16.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad4a6e564473f3d8e88c5f83dd98358df42d4b45e1b9df90088ec8b165ccc291"

[versions]
fabric = "0.18.4"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.3"]
